server:
  port: 8088
spring:
 application:
  name: gateway-service
 cloud:
  config:
   enabled: true
  gateway:
   discovery:
        locator:
          enabled: true
   routes:
   - id: ms-empleados #definido por mi solo es el nombre que se le quiera colocar
     uri: lb://ms-empleados # application name del ms : nombre del micro
     predicates: 
      - Path=/ms-empleados/** #path definido en el "RestController "Controller (/**) considera todo lo posterior a ese path
   - id: ms-clientes    #definido por mi solo es el nombre que se le quiera colocar
     uri: lb://ms-clientes # uri qye se define
     predicates:
      - Path=/ms-clientes/**  #path definido en el "RestController "Controller (/**) considera todo lo posterior a ese path
   - id: ms-circuit-brake    #definido por mi solo es el nombre que se le quiera colocar
     uri: lb://ms-circuit-brake
     predicates:
      - Path=/circuitBrakeMicro/**  #path definido en el "RestController "Controller (/**) considera todo lo posterior a ese path
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost      
      
      